### PR TITLE
Spanish support. i18n extendable.

### PR DESCRIPTION
**Pull request by maxiruani**
I have been able to abstract yout code from English specific and adapt it to Spanish. It should make it easier to support other languages too.
A tip, you should read and follow some javascript standard code conventions, that will help you a lot.
Excellent work.

### CODE REVIEW

**Comment by yamadapc** [comment]
@maxiruani I hadn't seen this until now. It looks like it's awesome! Thanks so much for the PR! If you haven't added yourself to the contributors sections you should do so. I'll have more time to look at it later today.

**Comment by yamadapc** [comment]
@kostasx I'm mentioning you here because I see you've done French and Greek as well. Once this is merged we can try to add that too with this scheme. I'll give both you guys push access after that.

**Comment by kostasx** [comment]
Thanks @yamadapc! I'll have to take a look at the code of @maxiruani and probably stick with that, since my own multilingual implementation is still buggy and underdeveloped. Once merged, I'll do my tests and maybe move them over here.

**Comment by maxiruani** [comment]
Thanks @yamadapc! The more languages this project support, the better it is. I will check later if I can add portuguese support too. I am not the best at it, but I could give a try.
@kostasx if you have doubts or need some help about the code, let me know and see if I can give you a hand.

**Comment by maxiruani** [comment]
I have made some fixes today. I have realized that the meaning of ```billion```, ```trillion``` and so on differs on each language. It depends the [scale (short or long)](http://en.wikipedia.org/wiki/Long_and_short_scales) the language use.
Now it is configurable through the config file of each language.
Tomorrow I will be adding the portuguese support.

**Comment by yamadapc** [comment]
@maxiruani I'm from Brazil, I can add portuguese support. If you could rebase this against the latest version of the code it'd be cool. Just a test name changed.

**Comment by maxiruani** [comment]
@yamadapc there it is the rebase. I have also pushed some portuguese partial support. The tests are missing, and the singulars and plurals translations after ```sextillion```
Thanks.

**Comment by yamadapc** [comment]
Okay. I'm just not merging this right now, because I don't want the README to not be in sync with the published version. I still have to go through my work day. Both you and @kostasx have push access now. Feel free to create a dev branch or something like that, but I don't think it's necessary.

**Comment by jperezruiz** [comment]
Amazing and very useful, thanks for implement i18'.

**Pull request merged**
