### PR TITLE
add configs to allow user can enter lang obj

### PR DESCRIPTION
**Pull request by nndung179**
**Problem:**
+ I install js-written-number from npm and everything is inside node_modules. And I want to pass our language into libs. I create file and put it all to node_modules. But everytime I re-install I have to put back lang file to node_modules/js-written-number.

**Solution:**
+ I suggest to pass another property to object "writtenNumber.defaults" called langObj. Let user can pass object follow structure of lang file from document.

### CODE REVIEW

**Comment by yamadapc** [comment]
Mm... That's interesting... You can always contribute with your language. This looks good to me, in my mind I'd keep the same option `lang`, but detect whether it's a string or an object, instead of adding another.

But I'll merge this today and patch, unless you want to change.

**Comment by nndung179** [comment]
@yamadapc you are right. I have just removed "langObj" and add conditions to check lang if lang is an object. Also, I have my own lang as json file and updated document of course.

**Comment by yamadapc** [comment]
Okay, I've added this onto master, tried to keep authorship. Thanks a lot, it's a great contribution.

**Comment by nndung179** [comment]
Hope it can help :)

**Pull request closed without merging**
