### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by tomByrer**

### CODE REVIEW

**Comment by yamadapc** [comment]
I have a strong impression your PR breaks test encoding. If you can remove those changes from the commit then amend/squash it'd be really nice.

**Comment by yamadapc** [comment]
Thanks!

**Comment by tomByrer** [comment]
The only line I directly touched is line 5: `writte` => `written`.  I did not directly touch the other lines; the GH online text editor did.  DId you commit with different line breaks than what GH has for default?

Feel free to fix it in your editor.  Might be time to make an `.editorconfig` if your linebreaks are particular.

**Comment by yamadapc** [comment]
I don't think it's about the line breaks. The lines which are different on this PR had non-ascii characters on them. Since your encoding fails to test on travis-ci, I don't really know what's the difference, but I guess mine works on both my machine and the CI.

Out of curiosity, do the tests pass on this branch, in your machine?

**Pull request closed without merging**
